spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11194753
spring.datasource.username: sql11194753
spring.datasource.password: ItUsYbAQeW
spring.jpa.show-sql: true

